name: Frontend Tests

on:
  push:
    branches:
      - frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./frontend

    - name: Build
      run: dotnet build --configuration Release --no-restore ./frontend

    - name: Test
      run: dotnet test --no-build --verbosity normal ./frontend
