name: Frontend Tests

on:
  push:
    branches:
      - main
      - frontend
  pull_request:
    branches:
      - main
      - frontend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore master-ugr.calculator.front-end/master-ugr.calculator.front-end.sln

      - name: Run frontend tests
        run: dotnet test master-ugr.calculator.front-end/tests/calculator.frontend.tests --no-restore --verbosity normal
