name: Snyk Scan

on:
  push:
    branches:
      - main
      - backend
      - frontend
  pull_request:
    branches:
      - main
      - backend
      - frontend

jobs:
  snyk:
    name: Snyk Security Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install Snyk CLI
      uses: snyk/actions/setup@master
      with:
        version: 'latest'

    - name: Run Snyk Test for Backend
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        snyk test --file=master-ugr.calculator.back-end/calculator.backend/calculator.backend.csproj --severity-threshold=high
    
    - name: Run Snyk Test for Frontend
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        snyk test --file=master-ugr.calculator.front-end/calculator.frontend/calculator.frontend.csproj --severity-threshold=high

    - name: Monitor Snyk (optional)
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        snyk monitor --file=Case3/master-ugr.calculator.front-end/calculator.frontend/calculator.frontend.csproj
